repos:
  # --- code formatter -------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 24.2.0          # pinned tag
    hooks:
      - id: black
        args: ["--line-length=88"]

  # --- import sorter --------------------------------------------------
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # --- static type checker -------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        # extra stubs you actually使っている場合だけ追加する
        additional_dependencies: ["types-tqdm"]     # ← optional
        args:
          - "--explicit-package-bases"
          - "--config-file=mypy.ini"                # use repo-root mypy.ini
