name: xfvcom
channels:
  - conda-forge
  - defaults
dependencies:
  # Python runtime
  - python=3.12.*

  # Core scientific packages
  - numpy
  - pandas
  - xarray
  - scipy
  - scikit-learn

  # Visualization packages
  - matplotlib
  - cartopy
  - pyproj
  - imageio
  - imageio-ffmpeg
  - moviepy

  # NetCDF support
  - netcdf4
  - h5netcdf
  - cftime

  # Additional required packages
  - tqdm
  - jinja2
  - pyyaml
  - chardet

  # Development tools
  - pytest
  - mypy
  - black
  - isort
  - ruff
  - ipykernel
  - jupyterlab

  # Type stubs for mypy
  - types-pyyaml
  - pandas-stubs

  # Pip dependencies (install after conda)
  - pip
  - pip:
      # Install xfvcom package in editable mode
      - -e .
