# ------------------------------------------
# pyproject.toml – build & metadata config
# ------------------------------------------

[build-system]
# Requirements for building the project (PEP 517)
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

# ------------------------------------------
# Project metadata (PEP 621)
# ------------------------------------------
[project]
name = "xfvcom"
version = "0.1.0"            # ← bump when you release
description = "FVCOM post-processing & visualisation toolkit"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.10"

# Project URLs displayed on PyPI
urls = { 
  "Homepage" = "https://github.com/your-org/xfvcom",
  "Issues"   = "https://github.com/your-org/xfvcom/issues"
}

# ------------------------------------------
# *Runtime* dependencies – install with `pip install xfvcom`
# ------------------------------------------
dependencies = [
  # core numerics / IO
  "numpy>=1.24",
  "xarray>=2024.1",
  "pandas>=2.2",
  "scipy>=1.11",
  "scikit-learn>=1.4",
  "pyproj>=3.6",
  "tqdm>=4.66",
  # visualisation / media
  "matplotlib>=3.8",
  "cartopy>=0.22",
  "imageio>=2",
  "moviepy>=1.0"
]

# ------------------------------------------
# Optional extras (install with `pip install xfvcom[dev]`)
# ------------------------------------------
[project.optional-dependencies]
dev = [
  # formatting / lint
  "black>=24",
  "isort>=5",
  # static type check
  "mypy>=1.15",
  "pandas-stubs",
  "types-tqdm",
  # testing
  "pytest>=8"
]

# ------------------------------------------
# setuptools-specific settings
# ------------------------------------------
[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
# include every subpackage under xfvcom
include = ["xfvcom*"]

# ------------------------------------------
# Tool configs (optional but handy)
# ------------------------------------------
[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
explicit_package_bases = true
