# -*- coding: utf-8 -*-
"""Generate a FVCOM ``RIVERS_NAMELIST*.nml`` from a river_dl YAML map.

Sibling CLI of :mod:`xfvcom.cli.make_river_nc_from_river_dl`: both
consume the **same** ``--river-map`` YAML.  This one emits the
``&NML_RIVER`` blocks that FVCOM reads from ``RIVERS_NAMELIST*.nml``;
the other one writes the matching combined-NC.  Running them in
sequence (see ``hydro/jobs/build_riv_sewer.sh``) makes the NC + NML
pair fully regenerable from a single YAML.

Schema (extended for this CLI; see ``make_river_nc_from_river_dl`` for
the parts shared with the NC adapter)::

    defaults:
      temp: 15.0
      salt: 0.0
    rivers:
      - name: EastArakawa
        node: 310                      # required for NML generation
        source: ${DATA_DIR}/.../discharge_hourly.nc
        vertical: uniform              # optional, default 'uniform'
      - name: Kisarazu
        kind: constant
        node: 1440
        flux: 0.2902
        temp: 10.0
        vertical: uniform

The optional ``--nml-fallback`` flag lets a partially-migrated YAML
that lacks ``node:`` for some entries fall back to the
``RIVER_GRID_LOCATION`` listed in an existing reference NML.  The
fallback is keyed by ``RIVER_NAME``.

``RIVER_FILE`` in every emitted block is the value of ``--river-file``;
``RIVER_FLUX_SCALE_LOCAL`` is hard-coded to ``1.0`` (new_bc baseline
convention — runtime calibration belongs in the run script, not in
this generated file).

Example
-------
::

    xfvcom-make-rivers-namelist \\
        --river-map  ~/Github/TB-FVCOM/hydro/input/river_dl_map_goto2023.yaml \\
        --river-file tb18_riv_sewer_riverdl_2020.nc \\
        --output     ~/Github/TB-FVCOM/input/goto2023/river/RIVERS_NAMELIST_sewer_new_bc.nml
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

HEADER_TEMPLATE = (
    " ! {filename}\n"
    " ! Auto-generated by xfvcom-make-rivers-namelist from {yaml_basename}.\n"
    " ! {n_entries} &NML_RIVER blocks (RIVER_FLUX_SCALE_LOCAL = 1.0 each).\n"
    " ! Do not edit by hand; re-run the build instead.\n"
)


BLOCK_TEMPLATE = (
    " &NML_RIVER\n"
    "  RIVER_NAME          = '{name}',\n"
    "  RIVER_FILE          = '{river_file}',\n"
    "  RIVER_GRID_LOCATION = {node},\n"
    "  RIVER_VERTICAL_DISTRIBUTION = '{vertical}'\n"
    "  RIVER_FLUX_SCALE_LOCAL = 1.0\n"
    "  /\n"
)


def _parse_fallback_nml(path: Path) -> dict[str, int]:
    """Read an existing RIVERS_NAMELIST.nml and return a
    ``{RIVER_NAME: RIVER_GRID_LOCATION}`` mapping.

    Tolerant to the existing TB-FVCOM hand-written layout (one key
    per line, single-quoted strings, blocks delimited by ``&NML_RIVER``
    and ``/``).  Lines starting with ``!`` are treated as comments.
    """
    name_re = re.compile(r"RIVER_NAME\s*=\s*'([^']+)'", re.IGNORECASE)
    grid_re = re.compile(r"RIVER_GRID_LOCATION\s*=\s*(-?\d+)", re.IGNORECASE)
    out: dict[str, int] = {}
    current_name: str | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("!", 1)[0]
        if not line.strip():
            continue
        m = name_re.search(line)
        if m:
            current_name = m.group(1)
            continue
        m = grid_re.search(line)
        if m and current_name is not None:
            out[current_name] = int(m.group(1))
            current_name = None
    return out


def _load_yaml_for_nml(
    yaml_path: Path,
    nml_fallback: dict[str, int],
) -> list[dict[str, Any]]:
    """Return the per-river dicts in YAML order with normalised keys.

    Each output dict carries: ``name``, ``node``, ``vertical``.  Other
    YAML fields are ignored (this CLI does not produce flux/temp/salt;
    those go through the NC adapter).
    """
    with yaml_path.open("r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}

    rivers_out: list[dict[str, Any]] = []
    unresolved: list[str] = []
    duplicate_nodes: dict[int, list[str]] = {}

    for rv in raw.get("rivers", []):
        name = rv.get("name")
        if not name:
            raise ValueError(f"river-map entry missing required key 'name': {rv!r}")
        node: int | None = None
        if "node" in rv:
            node = int(rv["node"])
        elif name in nml_fallback:
            node = nml_fallback[name]
        if node is None:
            unresolved.append(name)
            continue
        vertical = str(rv.get("vertical", "uniform"))
        rivers_out.append({"name": name, "node": node, "vertical": vertical})
        duplicate_nodes.setdefault(node, []).append(name)

    if unresolved:
        raise ValueError(
            "river-map entries missing 'node' (and no --nml-fallback "
            "match): " + ", ".join(unresolved)
        )

    dupes = {n: names for n, names in duplicate_nodes.items() if len(names) > 1}
    if dupes:
        raise ValueError(
            "two or more rivers share the same RIVER_GRID_LOCATION: "
            + "; ".join(f"node {n} -> {names}" for n, names in dupes.items())
        )

    return rivers_out


def _render(
    rivers: list[dict[str, Any]],
    river_file: str,
    yaml_basename: str,
    output_basename: str,
) -> str:
    header = HEADER_TEMPLATE.format(
        filename=output_basename,
        yaml_basename=yaml_basename,
        n_entries=len(rivers),
    )
    blocks = [
        BLOCK_TEMPLATE.format(
            name=r["name"],
            river_file=river_file,
            node=r["node"],
            vertical=r["vertical"],
        )
        for r in rivers
    ]
    return header + "".join(blocks)


def main() -> int:
    p = argparse.ArgumentParser(
        description=(
            "Generate a FVCOM RIVERS_NAMELIST*.nml from a river_dl YAML "
            "map.  Sibling of xfvcom-make-river-nc-from-river-dl; "
            "both consume the same --river-map YAML."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:

  xfvcom-make-rivers-namelist \\
      --river-map  hydro/input/river_dl_map_goto2023.yaml \\
      --river-file tb18_riv_sewer_riverdl_2020.nc \\
      --output     input/goto2023/river/RIVERS_NAMELIST_sewer_new_bc.nml
""",
    )
    p.add_argument(
        "--river-map",
        required=True,
        type=Path,
        help="YAML map; same file consumed by the NC adapter.",
    )
    p.add_argument(
        "--river-file",
        required=True,
        type=str,
        help=(
            "Filename written into every block's RIVER_FILE field. "
            "FVCOM prepends INPUT_DIR at run time, so pass a basename."
        ),
    )
    p.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Destination RIVERS_NAMELIST*.nml path.",
    )
    p.add_argument(
        "--nml-fallback",
        type=Path,
        default=None,
        help=(
            "Existing RIVERS_NAMELIST.nml to source RIVER_GRID_LOCATION "
            "from when the YAML row lacks a 'node:' field. Optional; "
            "used during a partial YAML migration."
        ),
    )
    args = p.parse_args()

    fallback: dict[str, int] = {}
    if args.nml_fallback is not None:
        if not args.nml_fallback.exists():
            print(
                f"[ERROR] --nml-fallback not found: {args.nml_fallback}",
                file=sys.stderr,
            )
            return 2
        fallback = _parse_fallback_nml(args.nml_fallback)

    try:
        rivers = _load_yaml_for_nml(args.river_map, fallback)
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 2

    if not rivers:
        print(
            "[ERROR] river-map produced zero blocks; nothing to write.",
            file=sys.stderr,
        )
        return 2

    text = _render(
        rivers,
        river_file=args.river_file,
        yaml_basename=args.river_map.name,
        output_basename=args.output.name,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(
        f"Wrote {args.output} ({len(rivers)} &NML_RIVER blocks; "
        f"RIVER_FILE='{args.river_file}')."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
