# -*- coding: utf-8 -*-
"""Tests for ``xfvcom-make-rivers-namelist``.

Covers YAML -> NML rendering, RIVER_GRID_LOCATION fallback via an
existing NML, duplicate-node detection, and the ``RIVER_FILE`` /
``RIVER_FLUX_SCALE_LOCAL = 1.0`` invariants.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from xfvcom.cli import make_rivers_namelist as mod

# re is imported above for use in test_render_basic_shape and the
# subprocess test.


FALLBACK_NML = """\
 &NML_RIVER
  RIVER_NAME          = 'EastArakawa',
  RIVER_FILE          = 'legacy.nc',
  RIVER_GRID_LOCATION = 310,
  RIVER_VERTICAL_DISTRIBUTION = 'uniform'
  /
 &NML_RIVER
  RIVER_NAME          = 'Shibaura',
  RIVER_FILE          = 'legacy.nc',
  RIVER_GRID_LOCATION = 1075,
  RIVER_VERTICAL_DISTRIBUTION = 'uniform'
  /
"""


@pytest.fixture
def fallback_nml(tmp_path: Path) -> Path:
    p = tmp_path / "fallback.nml"
    p.write_text(FALLBACK_NML, encoding="utf-8")
    return p


# ------------------------------------------------------------------
# 1. _parse_fallback_nml
# ------------------------------------------------------------------
def test_parse_fallback_nml_basic(fallback_nml: Path) -> None:
    out = mod._parse_fallback_nml(fallback_nml)
    assert out == {"EastArakawa": 310, "Shibaura": 1075}


def test_parse_fallback_nml_handles_comments(tmp_path: Path) -> None:
    p = tmp_path / "f.nml"
    p.write_text(
        "! header comment\n"
        " &NML_RIVER\n"
        "  RIVER_NAME = 'X', ! inline comment\n"
        "  RIVER_GRID_LOCATION = 42, ! grid here\n"
        "  /\n",
        encoding="utf-8",
    )
    assert mod._parse_fallback_nml(p) == {"X": 42}


# ------------------------------------------------------------------
# 2. _load_yaml_for_nml
# ------------------------------------------------------------------
def test_load_yaml_inline_node(tmp_path: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n"
        "  - name: A\n"
        "    node: 1\n"
        "    source: /tmp/a.nc\n"
        "  - name: B\n"
        "    node: 2\n"
        "    kind: constant\n"
        "    flux: 0.5\n"
        "    vertical: surface\n",
        encoding="utf-8",
    )
    rivers = mod._load_yaml_for_nml(y, nml_fallback={})
    assert rivers == [
        {"name": "A", "node": 1, "vertical": "uniform"},
        {"name": "B", "node": 2, "vertical": "surface"},
    ]


def test_load_yaml_with_fallback(tmp_path: Path) -> None:
    """YAML row without 'node:' resolves via the fallback NML."""
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n" "  - name: EastArakawa\n" "    source: /tmp/a.nc\n",
        encoding="utf-8",
    )
    rivers = mod._load_yaml_for_nml(y, nml_fallback={"EastArakawa": 310, "Other": 999})
    assert rivers == [
        {"name": "EastArakawa", "node": 310, "vertical": "uniform"},
    ]


def test_load_yaml_unresolved_node_raises(tmp_path: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n" "  - name: A\n" "    source: /tmp/a.nc\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="missing 'node'"):
        mod._load_yaml_for_nml(y, nml_fallback={})


def test_load_yaml_duplicate_node_raises(tmp_path: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n" "  - name: A\n" "    node: 7\n" "  - name: B\n" "    node: 7\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="same RIVER_GRID_LOCATION"):
        mod._load_yaml_for_nml(y, nml_fallback={})


def test_load_yaml_inline_node_overrides_fallback(tmp_path: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n" "  - name: A\n" "    node: 999\n",
        encoding="utf-8",
    )
    rivers = mod._load_yaml_for_nml(y, nml_fallback={"A": 100})
    assert rivers[0]["node"] == 999  # inline beats fallback


# ------------------------------------------------------------------
# 3. _render
# ------------------------------------------------------------------
def test_render_basic_shape() -> None:
    rivers = [
        {"name": "EastArakawa", "node": 310, "vertical": "uniform"},
        {"name": "Kisarazu", "node": 1440, "vertical": "uniform"},
    ]
    text = mod._render(
        rivers,
        river_file="combined.nc",
        yaml_basename="m.yaml",
        output_basename="RIVERS.nml",
    )
    # Header carries the basename and the entry count.
    assert "Auto-generated by xfvcom-make-rivers-namelist from m.yaml" in text
    assert "2 &NML_RIVER blocks" in text
    # Block contents.
    assert "RIVER_NAME          = 'EastArakawa'," in text
    assert "RIVER_FILE          = 'combined.nc'," in text
    assert "RIVER_GRID_LOCATION = 310," in text
    assert "RIVER_NAME          = 'Kisarazu'," in text
    assert "RIVER_GRID_LOCATION = 1440," in text
    # RIVER_FLUX_SCALE_LOCAL is hard-coded to 1.0 inside each block;
    # the header also mentions it once as documentation, so 2 blocks
    # + 1 header reference == 3 occurrences total.
    assert text.count("RIVER_FLUX_SCALE_LOCAL = 1.0") == 3
    # Two block delimiters (block-starts appear as ' &NML_RIVER\n'
    # with leading space; header mentions '&NML_RIVER' in plain text).
    block_starts = re.findall(r"^ &NML_RIVER$", text, flags=re.MULTILINE)
    assert len(block_starts) == 2


# ------------------------------------------------------------------
# 4. CLI end-to-end via subprocess (entry point)
# ------------------------------------------------------------------
def test_cli_entry_point(tmp_path: Path, fallback_nml: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n"
        "  - name: EastArakawa\n"
        "    source: /tmp/a.nc\n"  # node resolves via fallback
        "  - name: Kisarazu\n"
        "    kind: constant\n"
        "    node: 1440\n"
        "    flux: 0.2902\n",
        encoding="utf-8",
    )
    out_nml = tmp_path / "out.nml"
    cmd = [
        sys.executable,
        "-m",
        "xfvcom.cli.make_rivers_namelist",
        "--river-map",
        str(y),
        "--river-file",
        "combined.nc",
        "--output",
        str(out_nml),
        "--nml-fallback",
        str(fallback_nml),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    txt = out_nml.read_text(encoding="utf-8")
    # Both entries present, fallback-resolved node = 310 for EastArakawa.
    assert "RIVER_GRID_LOCATION = 310," in txt
    assert "RIVER_GRID_LOCATION = 1440," in txt
    # RIVER_FILE is what was passed in.
    assert re.search(r"RIVER_FILE\s+= 'combined.nc',", txt)


def test_cli_unresolved_node_exits_nonzero(tmp_path: Path, fallback_nml: Path) -> None:
    y = tmp_path / "m.yaml"
    y.write_text(
        "rivers:\n" "  - name: UnknownRiver\n" "    source: /tmp/x.nc\n",
        encoding="utf-8",
    )
    out_nml = tmp_path / "out.nml"
    cmd = [
        sys.executable,
        "-m",
        "xfvcom.cli.make_rivers_namelist",
        "--river-map",
        str(y),
        "--river-file",
        "combined.nc",
        "--output",
        str(out_nml),
        "--nml-fallback",
        str(fallback_nml),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    assert result.returncode != 0
    assert "missing 'node'" in result.stderr
    assert not out_nml.exists()
