# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) OS libs for Cartopy / PROJ / GEOS / GDAL
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libproj-dev proj-data proj-bin \
            libgeos-dev libgdal-dev

      # 3) Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 4) Dependencies
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      # 5) Static type check (optional)
      - name: Type check
        run: mypy xfvcom

      # 6) Run tests
      - name: Run tests
        run: pytest -q
